// Generates deterministic voronoi cell data used by <VoronoiBackground />.
// Run with: node scripts/generate-voronoi.mjs
// Output is written to src/components/brand/voronoi-cells.ts as a static const.

import { Delaunay } from "d3-delaunay";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = join(__dirname, "..", "src", "components", "brand", "voronoi-cells.ts");

const WIDTH = 1000;
const HEIGHT = 1000;
const SEED = 1337;
const GRID = 10;

function mulberry32(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function hexToRgb(hex) {
  const n = parseInt(hex.slice(1), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

function rgbToHex([r, g, b]) {
  const clamp = (v) => Math.round(Math.max(0, Math.min(255, v)));
  return `#${clamp(r).toString(16).padStart(2, "0")}${clamp(g).toString(16).padStart(2, "0")}${clamp(b).toString(16).padStart(2, "0")}`;
}

function lerp(a, b, t) {
  return a + (b - a) * t;
}

const STOPS = [
  { t: 0.0, color: hexToRgb("#FFB24A") },
  { t: 0.22, color: hexToRgb("#F87005") },
  { t: 0.42, color: hexToRgb("#8A3A12") },
  { t: 0.58, color: hexToRgb("#143A9A") },
  { t: 0.8, color: hexToRgb("#0B2E8C") },
  { t: 1.0, color: hexToRgb("#031D68") },
];

function colorAt(t) {
  const clamped = Math.max(0, Math.min(1, t));
  for (let i = 0; i < STOPS.length - 1; i++) {
    const a = STOPS[i];
    const b = STOPS[i + 1];
    if (clamped >= a.t && clamped <= b.t) {
      const local = (clamped - a.t) / (b.t - a.t);
      return rgbToHex([
        lerp(a.color[0], b.color[0], local),
        lerp(a.color[1], b.color[1], local),
        lerp(a.color[2], b.color[2], local),
      ]);
    }
  }
  return rgbToHex(STOPS[STOPS.length - 1].color);
}

const rand = mulberry32(SEED);
const points = [];
const cellW = WIDTH / GRID;
const cellH = HEIGHT / GRID;
for (let i = 0; i < GRID; i++) {
  for (let j = 0; j < GRID; j++) {
    const x = (i + 0.15 + rand() * 0.7) * cellW;
    const y = (j + 0.15 + rand() * 0.7) * cellH;
    points.push([x, y]);
  }
}

const delaunay = Delaunay.from(points);
const voronoi = delaunay.voronoi([0, 0, WIDTH, HEIGHT]);
const cells = [];

for (let i = 0; i < points.length; i++) {
  const poly = voronoi.cellPolygon(i);
  if (!poly) continue;

  let cx = 0;
  let cy = 0;
  for (const [px, py] of poly) {
    cx += px;
    cy += py;
  }
  cx /= poly.length;
  cy /= poly.length;

  const diag = (cx / WIDTH + (1 - cy / HEIGHT)) / 2;
  const jitter = (rand() - 0.5) * 0.06;
  const fill = colorAt(diag + jitter);

  const d =
    poly
      .map(([px, py], idx) => `${idx === 0 ? "M" : "L"}${px.toFixed(1)},${py.toFixed(1)}`)
      .join(" ") + " Z";

  cells.push({ d, fill });
}

const header = `// Auto-generated by scripts/generate-voronoi.mjs — do not edit manually.
// Regenerate with: node scripts/generate-voronoi.mjs

export interface VoronoiCell {
  d: string;
  fill: string;
}

export const VORONOI_VIEWBOX = { width: ${WIDTH}, height: ${HEIGHT} };

export const VORONOI_CELLS: VoronoiCell[] = [
`;

const body = cells
  .map((c) => `  { d: "${c.d}", fill: "${c.fill}" },`)
  .join("\n");

const footer = `\n];\n`;

writeFileSync(OUT_PATH, header + body + footer, "utf8");
console.log(`Wrote ${cells.length} cells to ${OUT_PATH}`);
